# Generated by Django 5.0.1 on 2024-02-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_number', models.CharField(max_length=13, unique=True)),
                ('frist_name_en', models.CharField(max_length=255)),
                ('last_name_en', models.CharField(max_length=255)),
                ('frist_name_th', models.CharField(max_length=255)),
                ('last_name_th', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(choices=[('B', 'Buddhism'), ('C', 'Christianity'), ('I', 'Islam'), ('H', 'Hinduism'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_issue', models.DateTimeField()),
                ('date_of_expiry', models.DateTimeField()),
                ('profile_image', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
